### ISSUE TITLE
[v3] Remove outline around box

### ISSUE THREAD

**Issue by gakimball** [zurb/joyride#210]
For mouse users, the outline around the box doesn't need to be there. This bit of CSS will disable the outline for mouse users only:

```scss
[data-whatinput='mouse'] .joyride {
  outline: 0;
}
```
